{{- if not .Values.instance.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.fullname" . }}-secret
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  instance-secret: {{ .Values.instance.secret | b64enc | quote }}
{{- end }}
---
{{- if and (eq .Values.database.type "postgres") (not .Values.database.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.fullname" . }}-db-secret
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-url: {{ .Values.database.postgres.url | b64enc | quote }}
{{- end }}
---
{{- if and (eq .Values.database.type "mysql") (not .Values.database.mysql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.fullname" . }}-db-secret
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-url: {{ .Values.database.mysql.url | b64enc | quote }}
{{- end }}
---
{{- if and (eq .Values.storage.type "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.fullname" . }}-s3-secret
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.storage.s3.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.storage.s3.secretAccessKey | b64enc | quote }}
  {{- if .Values.storage.s3.sessionToken }}
  aws-session-token: {{ .Values.storage.s3.sessionToken | b64enc | quote }}
  {{- end }}
{{- end }}
